### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by alxpettit** [MoriyaShiine/respawnable-pets#19]
What's the license on this code?

**Comment by MoriyaShiine** [comment]
If a github project has no license then it defaults to All Rights Reserved. What do you plan on doing? The only reason it's ARR is so I can deny Forge ports (I've had very bad experiences with them and don't want my code or mods associated with it), but otherwise I'll be very lenient on what you can do :).

**Comment by alxpettit** [comment]
I like to know that I can update a mod if it's abandoned, if I use it on one of my worlds. And if I'm going through the effort of maintaining a mod I'd prefer to release as GNU GPLv3 or a similar open license. That's all.

A bit odd that you'd choose this approach -- you could just license the code GNU GPLv3, but not the name or assets... and in this case, the code is so trivial that there's hardly anything that'd even be Forge-compatible.

**Comment by alxpettit** [comment]
Ah well. You do you. :woman_shrugging:

**Comment by MoriyaShiine** [comment]
Yeah I understand that. I don't plan on stopping modding any time soon, and if/when I do, I'll change the license, so you don't have to worry about that.
